driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-18.04
    run_list:
      - recipe[apt::default]

suites:
  - name: component_runit_supervisor_create
    run_list:
      - recipe[enterprise_test::setup]
      - recipe[enterprise_test::component_runit_supervisor_create]
    attributes:
      enterprise:
        name: testproject
  - name: component_runit_supervisor_delete
    run_list:
      - recipe[enterprise_test::setup]
      - recipe[enterprise_test::component_runit_supervisor_create]
      - recipe[enterprise_test::component_runit_supervisor_delete]
    attributes:
      enterprise:
        name: testproject
