Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'libraries/helpers.rb'

Style/RegexpLiteral:
  Exclude:
    - 'test/integration/component_runit_supervisor_create/serverspec/sysvinit_spec.rb'
    - 'test/integration/component_runit_supervisor_create/serverspec/upstart_spec.rb'
    - 'test/integration/component_runit_supervisor_delete/serverspec/sysvinit_spec.rb'
