Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'libraries/helpers.rb'

Style/RegexpLiteral:
  Exclude:
    - 'test/integration/component_runit_supervisor_create/inspec/sysvinit_spec.rb'
    - 'test/integration/component_runit_supervisor_create/inspec/upstart_spec.rb'
    - 'test/integration/component_runit_supervisor_delete/inspec/sysvinit_spec.rb'
